# Generated by Django 2.1.2 on 2018-10-13 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionset', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='que_options',
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionset.Question'),
        ),
    ]
