# Generated by Django 2.1.2 on 2018-10-13 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionset', '0002_auto_20181013_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='paper',
            field=models.ForeignKey(limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionset.Paper'),
        ),
    ]
