# Generated by Django 2.1.2 on 2018-10-20 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionset', '0006_auto_20181020_1105'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('que_num', 'paper')},
        ),
    ]
