# Generated by Django 2.1.3 on 2018-11-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionset', '0007_auto_20181020_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='correct_answer',
            field=models.BooleanField(default=False),
        ),
    ]
