# Generated by Django 2.1.3 on 2018-11-05 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionset', '0008_option_correct_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('para_marathi', models.TextField(null=True)),
                ('para_english', models.TextField(null=True)),
                ('para_img', models.ImageField(blank=True, null=True, upload_to='paragraphs/%Y/%m/%d/')),
                ('active', models.BooleanField(default=True)),
                ('paper', models.ForeignKey(limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionset.Paper')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='paragraph',
            field=models.ForeignKey(blank=True, limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionset.Paragraph'),
        ),
    ]
