# Generated by Django 2.1.3 on 2018-11-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionset', '0009_auto_20181105_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='name',
            field=models.CharField(default='ss', max_length=200),
        ),
    ]
