# Generated by Django 2.1.3 on 2018-11-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionset', '0011_auto_20181105_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='qc_level',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('First', 'First'), ('Second', 'Second'), ('Final', 'Final')], default='Not Started', max_length=50),
        ),
        migrations.AlterField(
            model_name='paper',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
