# Generated by Django 2.1.2 on 2018-10-09 18:40

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('type', models.CharField(choices=[('PRELIM', 'PRELIM'), ('MAINS', 'MAINS')], default='PRELIM', max_length=15)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('languauge', multiselectfield.db.fields.MultiSelectField(choices=[('MARATHI', 'MARATHI'), ('ENGLISH', 'ENGLISH')], max_length=15)),
                ('total_questions', models.IntegerField(default=100)),
                ('active', models.BooleanField(default=True)),
                ('exam', models.ForeignKey(limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionset.Exam')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_img', models.ImageField(upload_to='')),
                ('correct_answer', models.CharField(max_length=30)),
                ('tags', multiselectfield.db.fields.MultiSelectField(choices=[('MARATHI', 'MARATHI'), ('ENGLISH', 'ENGLISH')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2010, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='year',
            field=models.ForeignKey(limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionset.Year'),
        ),
        migrations.AlterUniqueTogether(
            name='paper',
            unique_together={('name', 'exam')},
        ),
    ]
