# Generated by Django 2.1.2 on 2018-10-09 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionset', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
    ]
