# Generated by Django 2.1.2 on 2018-10-01 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2010)),
            ],
        ),
        migrations.AlterField(
            model_name='paper',
            name='type',
            field=models.CharField(choices=[('PRELIM', 'PRELIM'), ('MAINS', 'MAINS')], max_length=15),
        ),
        migrations.AlterField(
            model_name='paper',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionset.Year'),
        ),
    ]
