# Generated by Django 2.1.2 on 2018-10-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionset', '0002_auto_20181009_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='question_text_marathi',
        ),
        migrations.AddField(
            model_name='question',
            name='question_text_english',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
