# Generated by Django 2.1.2 on 2018-10-09 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionset', '0003_auto_20181009_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_text_english',
            new_name='question_english',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_text_marathi',
            new_name='question_marathi',
        ),
    ]
