# Generated by Django 2.1.2 on 2018-10-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionset', '0004_auto_20181009_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_img',
            field=models.ImageField(null=True, upload_to='questions/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_marathi',
            field=models.TextField(null=True),
        ),
    ]
