# Generated by Django 2.1.2 on 2018-10-01 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionset', '0006_paper_total_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='year',
            field=models.ForeignKey(limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionset.Year'),
        ),
    ]
