# Generated by Django 2.1.2 on 2018-10-01 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionset', '0007_auto_20181001_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='paper',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='name',
            field=models.ForeignKey(limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionset.Exam'),
        ),
    ]
