# Generated by Django 2.1.2 on 2018-10-01 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionset', '0008_auto_20181001_1244'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paper',
            unique_together={('name', 'year', 'type')},
        ),
    ]
