# Generated by Django 2.1.2 on 2018-10-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionset', '0009_auto_20181001_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
