# Generated by Django 2.1.2 on 2018-10-03 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionset', '0010_exam_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='text',
        ),
    ]
