# Generated by Django 2.1.2 on 2018-10-09 18:23

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('questionset', '0011_remove_exam_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_img', models.ImageField(upload_to='')),
                ('correct_answer', models.CharField(max_length=30)),
                ('tags', multiselectfield.db.fields.MultiSelectField(choices=[('MARATHI', 'MARATHI'), ('ENGLISH', 'ENGLISH')], max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='type',
            field=models.CharField(choices=[('PRELIM', 'PRELIM'), ('MAINS', 'MAINS')], default='PRELIM', max_length=15),
        ),
        migrations.AddField(
            model_name='exam',
            name='year',
            field=models.ForeignKey(limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionset.Year'),
        ),
        migrations.AddField(
            model_name='paper',
            name='exam',
            field=models.ForeignKey(limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionset.Exam'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='paper',
            name='type',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='year',
        ),
        migrations.AlterUniqueTogether(
            name='paper',
            unique_together={('name', 'exam')},
        ),
    ]
